@startuml

package controllers{

class EditController {}
class ErrorController {}
class itemController {}
class ListController {}
class startController {
to do: make this puml look way better
and also add what these controllers do
}
class WarningController {}
}
package functions {
    class Edit {
    String: ToEdit
    ArrayList: List
    String[] item;
    -editListName()
    -editItemName()
    -editDueDate()
    -editDescription()
    -getArrayList()
    -getItem()
    -setToEdit(string)
    }

    class Item{
    +DueDateRegex(string)
    +DescriptionLength(string)
    -turnComplete()
    -turnIncomplete()
    }

    class List {
    -showAll()
    -showComplete()
    -showIncomplete()
    +deleteList()
    +DeleteAllItems()
    +NewList()
    +NewItem()
    +PrintWarning(string)
    +SaveList()
    +RemoveItem()
    }

    class Load {
    -loadFile(file)
    Error.printError(string)
    }

    class functions {
    I will move these into their specific things later
    for now I don't know which will need what if
     I'm being honest so I'mma point to all
     of them in  here aaaannnd yeah
    }
}
java.fx.application.Application <|-- TodoListApplication
TodoListApplication -- startController
java.fx.initializable -- startController
startController -- functions
EditController -- functions
ErrorController -- functions
itemController -- functions
ListController -- functions
startController -- functions
WarningController -- functions

@enduml